# Site settings
title: "Dr. Chia-Wei Hsu"
author_name: "Chia-Wei Hsu"
email: chiaweih@arizona.edu
description: "Chia-Wei Hsu's space"
baseurl: ""
url: ""
title_description: "Postdoctoral Research Associate (climate scientist) @ University of Arizona, Tucson."
title_image: "https://chiaweh2.github.io/figures/me.png"
google_analytics: "UA-20365477-4"
github_repository: https://github.com/chiaweh2
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: Hsu_Chia_Wei
github_username:  chiaweh2
linkedin_link: https://www.linkedin.com/in/chia-wei-hsu/


# Footer
footer_left: "Made by Jacob Tomlinson"
footer_right: "Modifide by Chia-Wei Hsu"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
