# Site settings
title: "Chia-Wei Hsu"
author_name: "Chia-Wei Hsu"
email: joedhsu@gmail.com
description: "Chia-Wei Hsu's space"
baseurl: ""
url: ""
title_description: "A geodesist, oceanagrapher, meteorologist, and climatologist"
title_image: "https://chiaweh2.github.io/IMG_2632.JPG"
google_analytics: "UA-20365477-4"
github_repository: https://github.com/chiaweh2
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
github_username:  chiaweh2
linkedin_link: https://www.linkedin.com/in/chia-wei-hsu/

# Footer
footer_left: "Made by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "Modifide by Chia-Wei Hsu"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
